# Generated by Django 4.2.6 on 2023-10-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_pass_in_otp_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sign_in_otp_verify',
            field=models.BooleanField(default=False),
        ),
    ]
