# Generated by Django 4.2.7 on 2023-11-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_item',
        ),
    ]
