# Generated by Django 4.2.7 on 2023-11-04 20:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0007_save_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='save_order',
            new_name='save',
        ),
    ]
