# Generated by Django 4.2.7 on 2023-11-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_save_order_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='cart.save'),
        ),
    ]
