# Generated by Django 4.2.7 on 2023-11-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cart_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_order',
            name='order_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
