# Generated by Django 4.2.7 on 2023-11-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cart_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='product',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='save',
        ),
    ]
