# Generated by Django 4.2.7 on 2023-11-09 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_save_product_remove_save_user_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='order_att',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
