# Generated by Django 4.2.6 on 2023-11-16 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_review_cmnt_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0016_order_items_order_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
