# Generated by Django 4.2.6 on 2023-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_deal_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_prod',
            field=models.BooleanField(default=False),
        ),
    ]
