# Generated by Django 4.2.6 on 2023-10-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
